<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ReperioNet.Benchmark</RootNamespace>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ReperioNet\ReperioNet.csproj" />
    <ProjectReference Include="..\..\src\ReperioNet.Languages.All\ReperioNet.Languages.All.csproj" />
  </ItemGroup>

</Project>
